name = "x12523-site"
main = "worker.py"
compatibility_date = "2025-12-23"
compatibility_flags = ["python_workers"]

[[d1_databases]]
binding = "DB"
database_name = "jianliku"
database_id = "66bd8675-ff3c-40db-9a12-10f554000244"

[[r2_buckets]]
binding = "UPLOADS_BUCKET"
bucket_name = "resume-uploads"

[[r2_buckets]]
binding = "EXPORTS_BUCKET"
bucket_name = "resume-exports"

[placement]
mode = "smart"